### ISSUE TITLE
typo in command line arguments in download.py

### ISSUE THREAD

**Issue by kiranchari** [YyzHarry/SubpopBench#2]
FYI: "--" prefix is missing in the `datasets` argument in download.py. This causes issues when passing arguments to this script.

`parser.add_argument('datasets', nargs='+', type=str, default=[`

change to

`parser.add_argument('--datasets', nargs='+', type=str, default=[`

https://github.com/YyzHarry/SubpopBench/blob/4d3dbbe21029666ef19d040e110ec22908640c5b/subpopbench/scripts/download.py#L691

**Comment by YyzHarry** [comment]
Hi, thanks for your interest! Here `datasets` was made to be positional arguments, therefore without '--' prefix.
