### ISSUE TITLE
difference between civilcomments and civilcommentsfine

### ISSUE THREAD

**Issue by kiranchari** [YyzHarry/SubpopBench#5]
May I know the difference between CivilComments and CivilCommentsFine in datasets.py? 

Which one should we use and which dataset is reported in the paper?

Thanks!

**Comment by hzhang0** [comment]
Hi, thank you for your interest, and sorry for the late reply!

All experiments in the paper were conducted using CivilCommentsFine in datasets.py.

Our code for processing CivilComments was taken from the [Simple Data Balancing repo](https://github.com/facebookresearch/BalancingGroups/tree/main). They describe the difference between the variants in more detail in their [paper](https://arxiv.org/pdf/2110.14503.pdf). Essentially:
- the training split for CivilComments (the coarse version) uses an attribute that can take _two_ possible values, corresponding to whether _any_ of the eight demographics appears in the comment.
- the training split for CivilCommentsFine uses an attribute that can take _eight_ possible values, corresponding to the eight demographics, but discards samples where none of the attributes appear.
