### ISSUE TITLE
early stopping using min_class:accuracy

### ISSUE THREAD

**Issue by kiranchari** [YyzHarry/SubpopBench#6]
Can I check if this is the right way to modify early_stopping to use **--es_metric min_class:accuracy** i.e. worst-class accuracy?

in eval_helper.py

`res['min_class'] = {'accuracy': min([res['per_class'][y]['recall'] for y in np.unique(targets)])}`

**Comment by YyzHarry** [comment]
Thank you for your interest. Just to clarify, 
1. In all the experiments, we didn't use early stopping in `train.py`; instead, we train all models to completion, and select the epoch using the model selection methods defined in the `collect_results.py` / `model_selection.py`
2. If you wanted to apply early stopping in training, the code that you have looks correct (we didn't test it though)
