### ISSUE TITLE
Clarification on Appendix E

### ISSUE THREAD

**Issue by kowshikthopalli** [YyzHarry/SubpopBench#7]
I want to know what is the backbone featurizer used for results in Appendix -E or is it averaged over all the different architectures. 
If it is the later, could you share the results due to individual architectures?

Thanks a lot

**Comment by hzhang0** [comment]
Hi Kowshik, thank you for your interest, and sorry for the late reply! The results shown in Appendix E are for the default set of architectures described in Appendix C.1. (ResNet-50 for images, BERT-base for text). The models in Appendix E were only trained using these architectures, and so we don't have results for additional architectures outside of what was reported in Appendix D.5.

**Comment by kowshikthopalli** [comment]
Thank you veru much.
Also do you plan to share the trained models checkpoints?

**Comment by hzhang0** [comment]
Not at this time unfortunately. We actually ran most experiments with `--skip_model_save` to conserve storage space, and so only saved the performance metrics but not the model checkpoints.
